# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Ability": "00_characters.ipynb",
         "Character": "00_characters.ipynb",
         "Wizard": "00_characters.ipynb",
         "Demon": "00_characters.ipynb",
         "GAME_TITLE": "01_game.ipynb",
         "init_player": "01_game.ipynb",
         "combat": "01_game.ipynb",
         "COMBAT_OPTIONS": "01_game.ipynb",
         "game_loop": "01_game.ipynb",
         "BOSS_BASE_HEALTH": "01_game.ipynb",
         "BOSS_BASE_DAMAGE": "01_game.ipynb"}

modules = ["characters.py",
           "game.py"]

doc_url = "https://ncoop57.github.io/wizardry/"

git_url = "https://github.com/ncoop57/wizardry/tree/main/"

def custom_doc_links(name): return None
