# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/00_characters.ipynb (unless otherwise specified).

__all__ = ['Ability', 'Character', 'Wizard', 'Demon']

# Cell
import random

from abc import ABC, abstractmethod

# Cell
class Ability:
    ability_types = ["fire", "water"]

    def __init__(self, damage, damage_type):
        self.damage = damage
        self.damage_type = damage_type

    @abstractmethod
    def __str__(self):
        if self.damage_type == "fire":
            return "a jet of fire shot towards"
        elif self.damage_type == "water":
            return "ice cold water is flung towards"


# Cell
class Character(ABC):
    def __init__(self, name, max_health, ability):
        self.name = name
        self.max_health = max_health
        self.current_health = max_health
        self.ability = ability
        self.level = 1

    @abstractmethod
    def attack(self, target):
        pass

    @abstractmethod
    def defend(self, attacker):
        pass

    def status(self):
        print(f"{self.name}'s Current Health: {self.current_health}")
        print(f"{self.name}'s Ability Damage: {self.ability.damage}")
        print(f"{self.name}'s Ability Type: {self.ability.damage_type}")

# Cell
class Wizard(Character):
    def __init__(self, name, max_health, ability):
        super().__init__(name, max_health, ability)

    def attack(self, target):
        print(f"From {self.name}'s wand, {self.ability} {target.name}")
        target.current_health -= self.ability.damage

    def defend(self):
        pass

    def level_up(self):
        self.level += 1
        self.max_health = self.max_health * self.level
        self.current_health = self.max_health
        self.ability.damage = self.ability.damage * self.level

# Cell
class Demon(Character):
    def __init__(self, name, max_health, damage):
        super().__init__(name, max_health, Ability(damage, "fire"))

    def attack(self, target):
        # scaling = random.uniform(0, 1)
        print(f"From {self.name}'s wand, {self.ability} {target.name}")
        target.current_health -= self.ability.damage

    def defend(self):
        pass