# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/01_game.ipynb (unless otherwise specified).

__all__ = ['GAME_TITLE', 'init_player', 'combat', 'COMBAT_OPTIONS', 'game_loop', 'BOSS_BASE_HEALTH', 'BOSS_BASE_DAMAGE']

# Cell
from .characters import Ability, Demon, Wizard

# Cell
GAME_TITLE = """\
Welcome to Wizardry!
"""

# Cell
def init_player():
    print(f"Hi there wizard, what is your specialty? {Ability.ability_types}")
    while True:
        ability_type = input()
        if ability_type in Ability.ability_types:
            break
        else:
            print(f"Invalid ability choice. What is your specialty? {Ability.ability_types}")
    return Wizard("Nathan", 100, Ability(10, ability_type))

# Cell
COMBAT_OPTIONS = ["attack"]

def combat(player, boss):
    print("Combat has begun!")
    while player.health > 0 and boss.health > 0:
        player.status()
        boss.status()
        print(f"What do you want to do? {COMBAT_OPTIONS}")
        player_move = input()
        if player_move not in COMBAT_OPTIONS:
            print("Not an option, you lose a move!")
        else:
            if player_move == "attack":
                player.attack(boss)

        boss.attack(player)

# Cell
BOSS_BASE_HEALTH = 50
BOSS_BASE_DAMAGE = 20

def game_loop(player, n = 10):
    for i in range(10):
        boss = Demon("Henry", BOSS_BASE_HEALTH * i, Ability(BOSS_BASE_DAMAGE * i, "fire"))
        print(f"A demon named {boss.name} appeared! They seem to have a chip on their shoulder and want to fight you.")
        combat(player, boss)
    pass